type User @model {
  userId: ID
  displayName: String
  products: [Product]
  surveyData: Survey
}

type Product {
  brand: String
  description: String
  name: String
  type: String
}

type Survey {
  FirstName: String
  LastName: String
}
